### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by mre** [zackify/cli.rs#38]
Thanks for the awesome service. Would it be possible to add HTTPS support?
You could e.g. use letsencrypt for it if you like.

No idea how the server is set up in the background, otherwise I would have had a look. 😉

**Comment by zackify** [comment]
This has nothing to do with my side. You are able to use https with your domain and letsencrypt once the dns record is in place

**Comment by zackify** [comment]
You have to give GitHub an hour or so to provision a cert if you turn on https in the settings.

**Comment by mre** [comment]
Ah alright, works now. Thanks! 😅
